<?php

namespace YYC\FoundationBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * BrandManagerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BrandManageRepository extends EntityRepository
{

}
