<?php

namespace AppBundle\Repository;

/**
 * AgencyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AgencyRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * 查找经销商
     */
    public function findAgency($query = false, $company = null, $code = null)
    {
        $qb = $this->createQueryBuilder('a')
            ->leftJoin('a.company', 'c')
        ;

        if ($company) {
            $qb->andWhere('c.company = :company' )
                ->setParameter('company', $company)
            ;
        }

        if ($code) {
            $qb->andWhere('a.code like :code or a.name like :code' )
                ->setParameter('code', '%'.$code.'%')
            ;
        }

        if ($query) {
            return $qb->getQuery();
        } 

        return $qb->getQuery()->getResult();
    }

    /**
     * 根据公司获取经销商名字列表，用于ajax下拉筛选
     */
    public function findAgencyNames($company = null, $name = '')
    {
        $qb = $this->createQueryBuilder('a')
            ->select('a.name')
        ;

        if ($company) {
            $qb->andWhere('a.company = :company' )
                ->setParameter('company', $company)
            ;
        }

        if ($name) {
            $qb->andWhere('a.name = :name' )
                ->setParameter('name', $name)
            ;
        }

        return $qb->getQuery()->getResult();
    }

    /**
     * 获取指定金融公司经销商id,名字
     */
    public function findAgencyNamesAndId($companyId = '')
    {
        $qb = $this->createQueryBuilder('a')
            ->select(array('a.id', 'a.name'))
        ;

        if (!empty($companyId)) {
            $qb->andWhere('a.company = :companyId' )
                ->setParameter('companyId', $companyId)
            ;
        }

        return $qb->getQuery()->getResult();
    }
}
