<?php

namespace AppBundle\Repository;

/**
 * AgencyRelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AgencyRelRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * 获取经销商名字列表，用于ajax下拉筛选
     */
    public function findAgencyNames($user = null, $company = null)
    {
        $qb = $this->createQueryBuilder('ar')
            ->leftJoin('ar.agency', 'a')
            ->select('a.name')
        ;

        if ($user) {
            $qb->andWhere('ar.user = :user')
                ->setParameter('user', $user)
            ;
        }

        if ($company) {
            $qb->andWhere('ar.company = :company')
                ->setParameter('company', $company)
            ;
        }

        return $qb->getQuery()->getResult();
    }

    /**
     * 获取公司名字列表，用于ajax下拉筛选
     */
    public function findCompanyNames($user)
    {
        $qb = $this->createQueryBuilder('ar')
            ->leftJoin('ar.company', 'c')
            ->select('c.company')
            ->where('ar.user = :user')
            ->setParameter('user', $user)
        ;

        return $qb->getQuery()->getResult();
    }

    /**
     * 用户查询
     */
    public function findUser($userId = null, $agencyId = null, $name = null, $mobile = null, $username = null, $companyId = null, $roles = null)
    {
        
        $qb = $this->createQueryBuilder('ua')
            ->leftJoin('ua.user', 'u')
            ->orderBy('u.id', 'ASC')
        ;

        if (!empty($userId)){
            $qb->andWhere('u.id != :userId')
                ->setParameter('userId', $userId)
            ;
        }

        if (!empty($agencyId)){
            $qb->andWhere('ua.agency in (:agencyId)')
                ->setParameter('agencyId', $agencyId)
            ;
        }

        if (!empty($companyId)){
            $qb->andWhere('ua.company = :companyId')
                ->setParameter('companyId', $companyId)
            ;
        }

        if (!empty($name)){
            $qb->andWhere('u.name like :name' )
                ->setParameter('name', '%'.$name.'%')
            ;
        }

        if (!empty($mobile)){
            $qb->andWhere('u.mobile like :mobile' )
                ->setParameter('mobile', '%'.$mobile.'%')
            ;
        }

        if (!empty($username)){
            $qb->andWhere('u.username like :username')
                ->setParameter('username', '%'.$username.'%')
            ;
        }

        if (!empty($roles)) {
            $qb->andWhere('u.roles in (:roles)')
                ->setParameter('roles', $roles)
            ;
        }

        return $qb->getQuery();
    }

     /**
     * 获取指定用户的等级
     */
    public function findAgencyRelsGrade($user)
    {
        $qb = $this->createQueryBuilder('ar')
            ->where('ar.user = :user')
            ->setParameter('user', $user)
            ->select(array('ar.grade'))
        ;

        return $qb->getQuery()->getResult();
    }
}
