<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * AnnouncementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnnouncementRepository extends EntityRepository
{

    public function getAnnouncements($start, $limit){
        $qb = $this->createQueryBuilder("a");
        $qb->select("a")
            ->andWhere("a.enabled = :enabled")
            ->setParameter("enabled", true)
            ->orderBy("a.id", "DESC")
            ->setFirstResult($start)
            ->setMaxResults($limit);
        return $qb->getQuery()->getArrayResult();

    }


}
