<?php

namespace AppBundle\Repository;

/**
 * ApplyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ApplyRepository extends \Doctrine\ORM\EntityRepository
{
	/**
     * 授权申请列表
     */
    public function findApply($status = null, $mobile = null, $startDate = null, $endDate = null, $company = null, $agency = null, $grade = null)
    {
        $qb = $this->createQueryBuilder('a')
            ->orderBy('a.id', 'DESC')
        ;

        if ($status !=3 && $status != null){
            $qb->andWhere('a.status = :status' )
                ->setParameter('status', $status)
            ;
        }

        if (!empty($mobile)){
            $qb->andWhere('a.mobile like :mobile' )
                ->setParameter('mobile', '%'.$mobile.'%')
            ;
        }

        if (!empty($startDate)){
            $qb->andWhere('a.createdAt >= :startDate')
                ->setParameter('startDate', $startDate)
            ;
        }

        if (!empty($endDate)){
            $qb->andWhere('a.createdAt <= :endDate')
                ->setParameter('endDate', date('Y/m/d/ H:i:s', strtotime('+1 day -1 second', strtotime($endDate))))
            ;
        }

        if (!empty($company)){
            $qb->andWhere('a.company = :company' )
                ->setParameter('company', $company)
            ;
        }

        if (!empty($agency)){
            $qb->andWhere('a.agency in (:agency)' )
                ->setParameter('agency', $agency)
            ;
        }

        if (!empty($grade)) {
            $qb->andWhere('a.grade in (:grade)')
                ->setParameter('grade', $grade)
            ;
        }

        return $qb->getQuery();
    }
}
