<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TrainingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TrainingRepository extends EntityRepository
{

    public function getTrainings($start, $limit){
        $qb = $this->createQueryBuilder("t");
        $qb->select("t")
            ->andWhere("t.enabled = :enabled")
            ->setParameter("enabled", true)
            ->orderBy("t.id", "DESC")
            ->setFirstResult($start)
            ->setMaxResults($limit);
        return $qb->getQuery()->getArrayResult();

    }


}
