<?php

namespace AppBundle\Repository;

/**
 * WhiteListRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WhiteListRepository extends \Doctrine\ORM\EntityRepository
{
}
